### ISSUE TITLE
Startscreen entwickeln

### ISSUE THREAD

**Issue by MathiasSotta** [MathiasSotta/puf-ss18#12]
- [x] Startscreen als View implementieren
- [x] Startscreen-Grafiken und Interaktionselemente (StartButton, Highscoreliste) implementieren
- [x] Eingabe von Name für Player1 und Player1, Speicherung im jeweiligen Player Objekt

**Comment by KatZieg** [comment]
https://stackoverflow.com/questions/13003323/javafx-how-to-change-stage
