### ISSUE TITLE
Bombe wird manchmal im nächsten Grid Element gedropped

### ISSUE THREAD

**Issue by awdng** [MathiasSotta/puf-ss18#14]
![bomb_onto_block](https://user-images.githubusercontent.com/618852/42529171-01579f7a-847e-11e8-8505-0d2b73ab53d1.png)

Wenn man zwischen den Grid Elementen steht erscheint sie manchmal in dem Element wo der Spieler eigentlich noch nicht angekommen ist

**Comment by MathiasSotta** [comment]
Gefixt. Ich habe die Methode jetzt stark vereinfacht. Die Bombenposition wird nun anhand der Player-Center Position berechnet und platziert. Sie landet also immer in dem Tile, wo sich der Mittelpunkt des Players befindet.
