### ISSUE TITLE
Explosion fügt im Zentrum keinen Schaden zu

### ISSUE THREAD

**Issue by awdng** [MathiasSotta/puf-ss18#15]
![destr_block_not_destroyed](https://user-images.githubusercontent.com/618852/42529231-358e20de-847e-11e8-890d-bb4090ccbac5.png)
![enemy_not_destroyed](https://user-images.githubusercontent.com/618852/42529235-376524f2-847e-11e8-8718-afa678edbef0.png)

**Comment by MathiasSotta** [comment]
Fixed in Bomb.java:         
// explosion center
        this.explosion.add(new Rectangle2D(getX(), getY(), getFitWidth(), getFitHeight()));
