### ISSUE TITLE
Bombenkollision entwickeln

### ISSUE THREAD

**Issue by MathiasSotta** [MathiasSotta/puf-ss18#2]
Tipp von Ilse: unsichtbaren circle platzieren und für Koll.abfrage verwenden

- [x]  bei der Platzierung liegt **bomb** (sichtbar) unter **player**

- [x]  bewegt sich **player** von der **bomb** weg (steht in Bezug auf die Spielmatrix vollständig auf einem anderen Feld), so wird das Feld für die Lebensdauer der **bomb** nicht begehbar (analog UndestructableBlock)

**Comment by MathiasSotta** [comment]
** bei der Platzierung liegt **bomb** (sichtbar) unter **player**
** bewegt sich **player** von der **bomb** weg (steht in Bezug auf die Spielmatrix vollständig auf einem anderen Feld), so wird das Feld für die Lebensdauer der **bomb** nicht begehbar (analog UndestructableBlock)

**Comment by awdng** [comment]
https://github.com/MathiasSotta/puf-ss18/commit/19d0136d2345e949834398d504c75c271936e869

TODO: Spieler sollten von Bomben geblockt werden
