### ISSUE TITLE
Bombe  platzieren

### ISSUE THREAD

**Issue by MathiasSotta** [MathiasSotta/puf-ss18#4]
- [x]  die Bombe kann auf freien Flächen (!=DestructibleBlock || !=UndesctructibleBlock) platziert werden

- [x]  die Bombe soll entsprechend der Spielmatrix immer genau auf der Mitte des Feldes platziert werden, auf dem sich **player** befindet

**Comment by awdng** [comment]
https://github.com/MathiasSotta/puf-ss18/commit/19d0136d2345e949834398d504c75c271936e869

Fehlt: Lock auf Spielmatrix

**Comment by MathiasSotta** [comment]
Lock funktioniert
