### ISSUE TITLE
Bombenexplosion entwickeln

### ISSUE THREAD

**Issue by MathiasSotta** [MathiasSotta/puf-ss18#7]
Lebenszyklus einer Bombe:
* Bombe wird gelegt > Timer der Bombe wird gestartet
* Timer läuft ab > die Bombe explodiert und erzeugt Zerstörung innerhalb ihres Explosionsradius
* DestructibleBlock(s), **player** oder **enemy** innerhalb des Explosionsradius werden zerstört
* DestructibleBlock(s) verschwinden nach Zerstörung durch Explosion

- [x] die Bombe explodiert nach Ablauf des Timers
- [x] die Bombe soll initial einen Explosionsradius von 2 Matrixfeldern haben und zwar in alle möglichen Bewegungsrichtungen (= N, S, E, W)

Schematische Darstellung der Explosionsausbreitung: 

             |
             |
         ─ ─ O ─ ─
             |
             |

**Comment by awdng** [comment]
Beispiel aus Unity3d, denke vom Prinzip her ist das so wie wir es auch wollen: https://www.raywenderlich.com/167052/bomberman-tutorial-fun-blowing-friends

Muss mal sehen wie man die einzelnen Dinge am besten in JavaFX adaptiert

**Comment by awdng** [comment]
Erste Implementierung in https://github.com/MathiasSotta/puf-ss18/commit/19d0136d2345e949834398d504c75c271936e869

Grafik/Animation fehlt noch
